name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    - name: Get lock file version from script and set it as variable
      id: id
      run: echo "::set-output name=PACKAGE_LOCK_VERSION::$(node index.js)"

    - name: Output PACKAGE_LOCK_VERSION
      run: echo PACKAGE_LOCK_VERSION ${{ steps.id.outputs.PACKAGE_LOCK_VERSION }}

    - name: Check for desired package-lock version and fail build in case of version mismatch
      if: ${{ steps.id.outputs.PACKAGE_LOCK_VERSION != 1 }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Package-lock.json version mismatch.')