name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v3

    - name: Install node and npm
      uses: actions/setup-node@v3
      with:
        node-version: '14'
        registry-url: https://registry.npmjs.org/

    - name: Install npm dependencies
      run: npm install

    - name: Get lock file version from script and set it as variable and set DESIRED_PACKAGE_LOCK_VERSION as variable
      id: id1
      env:
        DESIRED_PACKAGE_LOCK_VERSION: 1
      run: |
        echo "DESIRED_PACKAGE_LOCK_VERSION=${DESIRED_PACKAGE_LOCK_VERSION}" >> $GITHUB_OUTPUT

    - name: Import package-lock.json and save in PACKAGE_LOCK_FILE variable
      id: id2
      run: |
        package_lock_file_version=`cat ./package-lock.json | jq '.lockfileVersion'`
        echo "PACKAGE_LOCK_VERSION=${package_lock_file_version}" >> $GITHUB_OUTPUT

    - name: Output variable
      id: output
      run: |
        echo DESIRED_PACKAGE_LOCK_VERSION ${{ steps.id1.outputs.DESIRED_PACKAGE_LOCK_VERSION }}
        echo PACKAGE_LOCK_VERSION ${{ steps.id2.outputs.PACKAGE_LOCK_VERSION }}

    - name: Check for desired package-lock version and fail build in case of version mismatch
      if: ${{ steps.id1.outputs.DESIRED_PACKAGE_LOCK_VERSION != steps.id2.outputs.PACKAGE_LOCK_VERSION }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Package-lock.json version mismatch.')
