name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout latest commit
      uses: actions/checkout@v2

    - name: Install node and npm
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'

    - name: Install npm dependencies
      run: npm install

    # - name: Import package-lock.json
    #   id: id2
    #   run: |
    #     echo "::set-output name=PACKAGE_LOCK_FILE::$(cat ./package-lock.json)"

    - name: Import package-lock.json
      id: id2
      run: |
        package_lock=`cat ./package-lock.json`

        package_lock="${package_lock//'%'/'%25'}"
        package_lock="${package_lock//$'\n'/'%0A'}"
        package_lock="${package_lock//$'\r'/'%0D'}"

        echo "::set-output name=PACKAGE_LOCK_FILE::$package_lock"

    - name: Output package-lock.json 1
      run: |
        echo PACKAGE_LOCK_FILE ${{ fromJson(steps.id2.outputs.PACKAGE_LOCK_FILE) }}

    - name: Output package-lock.json 2
      run: |
        echo "${{ fromJson(steps.id2.outputs.PACKAGE_LOCK_FILE).lockfileVersion }}"

    - name: Get lock file version from script and set it as variable and set DESIRED_PACKAGE_LOCK_VERSION as variable
      id: id
      env:
        DESIRED_PACKAGE_LOCK_VERSION: 1
      run: |
        echo "::set-output name=PACKAGE_LOCK_VERSION::$(node index.js)"
        echo "::set-output name=DESIRED_PACKAGE_LOCK_VERSION::$DESIRED_PACKAGE_LOCK_VERSION"

    - name: Output variable
      run: |
        echo PACKAGE_LOCK_VERSION ${{ steps.id.outputs.PACKAGE_LOCK_VERSION }}
        echo DESIRED_PACKAGE_LOCK_VERSION ${{ steps.id.outputs.DESIRED_PACKAGE_LOCK_VERSION }}

    - name: Check for desired package-lock version and fail build in case of version mismatch
      if: ${{ steps.id.outputs.PACKAGE_LOCK_VERSION != steps.id.outputs.DESIRED_PACKAGE_LOCK_VERSION }}
      uses: actions/github-script@v3
      with:
        script: core.setFailed('Package-lock.json version mismatch.')
